[[redirects]]
  from = "/old-path/:path"
  to = "/new-path/:path"
  status = 301
  force = true

[build]
  command = "npm install --production=false && (npm run verify-deployment || true) && npm run build"
  publish = "dist"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.17.0"
  NODE_ENV = "production"
  FIREBASE_PRIVATE_KEY = "${FIREBASE_PRIVATE_KEY}"
  FIREBASE_CLIENT_EMAIL = "${FIREBASE_CLIENT_EMAIL}"
